import { createElement } from 'lwc';
import Course_Enrollment_Monitor from 'c/course_Enrollment_Monitor';

describe('c-course-enrollment-monitor', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-course-enrollment-monitor', {
            is: Course_Enrollment_Monitor
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});